#' Variate Generation for <%= distro %> Distribution
#'
#' @param n number of observations
#' @param antithetic if \code{FALSE} (default), inverts \eqn{u} = uniform(0,1)
#'     variate(s) generated via either \code{\link[=runif]{stats::runif}} or
#'     \code{\link[=rstream.sample]{rstream::rstream.sample}}; otherwise, uses
#'     \eqn{1 - u}
#' @param asList if \code{FALSE} (default), output only the generated
#'     random variates; otherwise, return a list with components suitable for
#'     visualizing inversion. See return for details
#'
#' @details
#'   Generates random variates from the <%= distrolc %> distribution.
#'
#'   <%= distro %> variates are generated by inverting uniform(0,1) variates
#'   produced either by \code{\link[=runif]{stats::runif}} (if \code{stream} is
#'   \code{NULL}) or by \code{\link[=rstream.sample]{rstream::rstream.sample}}
#'   (if \code{stream} is not \code{NULL}).
#'   In either case, \code{\link[=q<%= funct %>]{stats::q<%= funct %>}} is used to
#'   invert the uniform(0,1) variate(s).
#'   In this way, using \code{<%= vfunct %>} provides a monotone and synchronized
#'   binomial variate generator, although not particularly fast.
#'
#'   The stream indicated must be an integer between 1 and 25 inclusive.
#'
#' @return
#'   If \code{asList} is FALSE (default), return a vector of random variates.
#'
#'   Otherwise, return a list with components suitable for visualizing inversion,
#'   specifically:
#'     \item{u}{        A vector of generated U(0,1) variates }
#'     \item{x}{        A vector of <%= distrolc %> random variates }
#'     \item{quantile}{ Parameterized quantile function }
#'     \item{text}{     Parameterized title of distribution }
#'
#' @examples
#'  set.seed(8675309)
#'  # NOTE: following inverts rstream::rstream.sample using stats::q<%= funct %>
#'  <%= vfunct %>(3, <%= arglong %>)
#'
#'  set.seed(8675309)
#'  # NOTE: following inverts rstream::rstream.sample using stats::q<%= funct %>
#'  <%= vfunct %>(3, <%= argshort %>, stream = 1)
#'  <%= vfunct %>(3, <%= argshort %>, stream = 2)
#'
#'  set.seed(8675309)
#'  # NOTE: following inverts rstream::rstream.sample using stats::q<%= funct %>
#'  <%= vfunct %>(1, <%= argshort %>, stream = 1)
#'  <%= vfunct %>(1, <%= argshort %>, stream = 2)
#'  <%= vfunct %>(1, <%= argshort %>, stream = 1)
#'  <%= vfunct %>(1, <%= argshort %>, stream = 2)
#'  <%= vfunct %>(1, <%= argshort %>, stream = 1)
#'  <%= vfunct %>(1, <%= argshort %>, stream = 2)
#'
#'  set.seed(8675309)
#'  variates <- <%= vfunct %>(1000, <%= argshort %>, stream = 1)
#'  set.seed(8675309)
#'  variates <- <%= vfunct %>(1000, <%= argshort %>, stream = 1, antithetic = TRUE)
#'
#' @keywords distribution
#'
#' @concept random variate generation
#'
#' @author
#'    Barry Lawson (\email{blawson@@richmond.edu}), \cr
#'    Larry Leemis (\email{leemis@@math.wm.edu}), \cr
#'    Vadim Kudlay (\email{vadim.kudlay@@richmond.edu})
#'
#' @seealso \code{\link{rstream}}, \code{\link{set.seed}},
#'          \code{\link[=runif]{stats::runif}}
